### PR TITLE
Fix #225, Fix #236: use temporary RTs with the active camera dimensions to fix VR issues

### LINKED ISSUE #225: Sky renders incorrectly in KerbalVR apparently due to ocean renderer commandbuffer
When using scatterer 0.0878 or 0.0880 with KerbalVR, the sky generally will appear black - unless you look up.  There is a hard clipping line where the sky is drawn normally.  I think I've tracked this down to some kind of problem with the ocean meshrenderer commandbuffer.  The line that separates "good" from "bad" corresponds to where this command buffer draws into the depth/stencil buffer.

image

image

https://drive.google.com/file/d/1sm1NxsKQBWyqwqBKXCNrEf9JjYBC9QBl/view?usp=sharing

### LINKED ISSUE #236: Scatterer causes the game window resolution to affect VR image quality
https://github.com/FirstPersonKSP/Kerbal-VR/issues/331#issuecomment-3249831242

There's a number of places in scatterer that are using screen.width and height and probably need to do something more intelligent for the VR case.  If these are temporary render targets, the strategy I used in https://github.com/LGhassen/Scatterer/pull/226 should be pretty painless.

### PR DESCRIPTION
**Pull request by JonnyOThan**
fixes rendering in VR because it automatically gets the right size no matter what the camera dimensions are

also doesn't require special screenshot handling

### CODE REVIEW

File: scatterer/Effects/Proland/Ocean/OceanRenderingHook.cs [hunk 1]
```diff
@@ -139,79 +156,21 @@ private void RecreateCommandBuffer()
...
                 {
-                    CreateRenderTextures();
                     RecreateCommandBuffer();
                 }
 
-				bool screenShotModeEnabled = GameSettings.TAKE_SCREENSHOT.GetKeyDown(false);
-				if (oceanScreenShotModeEnabled != screenShotModeEnabled)
-                {
-					// Resize textures
-					int superSizingFactor = screenShotModeEnabled ? Mathf.Max(GameSettings.SCREENSHOT_SUPERSIZE, 1) : 1;
```
Comment (LGhassen) [inline scatterer/Effects/Proland/Ocean/OceanRenderingHook.cs:209]: I am pretty sure that temporary RTs don't detect/work correctly for supersized screenshots. You can leave it like this for now, but I have a branch with new ocean features using tempRTs which I will probably have to check after merging this.

Comment (JonnyOThan) [reply scatterer/Effects/Proland/Ocean/OceanRenderingHook.cs:209]: I did test this and it seemed fine.

https://imgur.com/e7X5u2l
